In [1]:
# p.109 4.4.2 ニューラルネットワークに対する勾配
import sys, os
sys.path.append(os.pardir)
import numpy as np
from functions import softmax, cross_entropy_error
from gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3) # ガウス分布で初期化
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [2]:
net = simpleNet()
print(net.W) # 重みパラメータ

[[-1.1339412   0.52806248  1.25340137]
 [-0.11858398  1.35673698 -0.13263989]]


In [3]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-0.7870903   1.53790077  0.63266492]


In [4]:
np.argmax(p) # 最大値のインデックス

1

In [5]:
t = np.array([0, 0, 1]) # 正解ラベル
net.loss(x, t)

1.3121866847067243

In [6]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.03905563  0.39940585 -0.43846148]
 [ 0.05858344  0.59910878 -0.65769222]]


In [7]:
f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.03905563  0.39940585 -0.43846148]
 [ 0.05858344  0.59910878 -0.65769222]]
